---
all:
  children:
    local:
      hosts:
        vm1.local.neogrid.com:
          ansible_host: 
          ansible_user: 
          #ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_pass: ""


    dev:
      hosts:
        vm2.dev.neogrid.com:
          ansible_host: 
    pre:
      hosts:
        vm3.pre.neogrid.com:
          ansible_host: 
    prd:
      hosts:
        vm4.prd.neogrid.com:
          ansible_host: 
        vm5.prd.neogrid.com:
          ansible_host:          
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/id_rsa