---
- name: Restart podman service
  ansible.builtin.systemd:
    name: podman
    state: restarted
    daemon_reload: true

- name: Restart podman socket
  ansible.builtin.systemd:
    name: podman.socket
    state: restarted
    daemon_reload: true
